### ISSUE TITLE
Unhandled promise if the URL is invalid

### ISSUE THREAD

**Issue by mcaubrey** [ajhenry/react-google-slides#40]
If you give the component an invalid URL, an unhandled error is thrown

```
Unhandled Runtime Error
Error: Failed to fetch presentation key, check the presentation url
```

I'd like it if there was a way to handle this more gracefully. For example, you could come up with something to display as default (such as a blank box with a red X), and then allow users to pass in a different component if they want to display their own custom content on error.

**Comment by ajhenry** [comment]
Yea you’re absolutely right about throwing an error being the wrong thing to do here. I wrote this package when I was first learning React and this should be changed.

I can update this later this weekend to instead accept an error component like you mentioned

**Comment by mtuckerbd** [comment]
> Yea you’re absolutely right about throwing an error being the wrong thing to do here. I wrote this package when I was first learning React and this should be changed.
> 
> I can update this later this weekend to instead accept an error component like you mentioned

Any update on this? Trying to work around this issue currently.

**Comment by ajhenry** [comment]
Hey there, I haven’t gotten to this yet but can probably take a look at it today

**Comment by ajhenry** [comment]
Additionally, if someone else wants to take a crack at this, I'm imagining we'll add another optional prop called `errorComponent` that takes in a React Element/Node that gets rendered on error and no longer throw.

If there isn't an error prop we just don't display the component

**Comment by ajhenry** [comment]
Fixed this in https://github.com/ajhenry/react-google-slides/commit/72c658d6341fb375df69c66b930ba9488ca23323

You'll need to perform a major upgrade to see the change 🤓 

```
npm i react-google-slides@latest
yarn add react-google-slides@latest
```
